<?php
/**
*This module blocked pages if user select language, what's not exists 
*/

function access_denied_form_node_form_alter(&$form, & $form_state) {
  $languages = language_list('enabled'); 
  foreach($languages as $key => $value) {
    $valang[] = $value;
    foreach($value as $k => $val) {
      $lang[$k] = $val->name;
    }
  }
  $form['addmenu'] = array(
    '#description'    => t('In this field you may blocked content for user on this languages'),
    '#type'           => 'fieldset',
    '#title'          => 'Blocked node for this language',
    '#group'          => 'additional_settings',
    '#weight'         => -99,
  );
  $form['addmenu']['addlanguage'] = array(  
    '#type'     => 'checkboxes',
    '#title'    => t('For what language access denied?'),
    '#options'  => $lang,
  );
  return $form;
}
function access_denied_node_submit($node, $form, &$form_state) {
  $languages = language_list('enabled'); 
  $check = $form_state['values']['addlanguage'];
  foreach($check as $key => $value){
    $query = db_insert('tablang')
    ->fields(array(
      'checkbox'=>$value,
      'node'=>$node->nid,
      'lang'=>$key,
    ))
    ->execute();
  }  
}  
function access_denied_node_delete($node) {
  db_delete('tablang')->condition('node', $node->nid)->execute();
}
function access_denied_node_access($node, $op, $account) {
 $query = db_select('tablang', 't')
  ->fields('t', array('node', 'lang','checkbox'))
  ->execute(); 
  while ($value = $query ->fetchAssoc()){
  $nid = $value['node'];
  $lang = $value['lang'];
  $checkbox = $value['checkbox'];
  }
   if ($node->nid == $nid){
   if  ($checkbox > 0){  
  return NODE_ACCESS_DENY;
}}}

